# Generated by Django 3.0.7 on 2020-06-26 08:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200625_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
    ]
