# Generated by Django 3.0.7 on 2020-06-26 19:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200626_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
