# Generated by Django 3.0.7 on 2020-06-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200626_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_credit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
